name: "Build/test (virtual)"
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: mcr.microsoft.com/ccf/app/dev:4.0.16-virtual
      env:
        # Additional CMake flags.
        PLATFORM: virtual
        CMAKE_BUILD_TYPE: Debug
        # These make CI print all the errors, rather than stopping early.
        CXXFLAGS: -ferror-limit=0
        NINJA_FLAGS: -k 0
    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Work-around for https://github.com/actions/runner/issues/2033
      - name: Work around git safe.directory in container
        run: chown -R $(id -u):$(id -g) $PWD
      - run: apt-get update && apt-get install -y libcurl4-openssl-dev
      - run: ./build.sh
      - run: ./test.sh
